#include <stdint.h>

/* Verified against np21w rev103 bios/bios09.c, bios/bios18.c and
   bios/biosmem.h. These are PC-98 BIOS data addresses, not IBM-PC BDA
   addresses. Each queue word contains the character in the low byte and
   the scan code in the high byte. */
#define PC98_KB_BUFFER_START 0x0502
#define PC98_KB_BUFFER_END   0x0522
#define PC98_KB_HEAD         0x0524
#define PC98_KB_TAIL         0x0526
#define PC98_KB_COUNT        0x0528
#define PC98_KB_CAPACITY     16

/* np21w rev103 keystat.h and bios/bios09.c key numbers. */
#define PC98_SCAN_ESC        0x00
#define PC98_SCAN_BACKSPACE  0x0e
#define PC98_SCAN_TAB        0x0f
#define PC98_SCAN_RETURN     0x1c
#define PC98_SCAN_SPACE      0x34

static volatile unsigned char __far *bios_byte(unsigned short offset)
{
    return (volatile unsigned char __far *)(unsigned long)offset;
}

static volatile unsigned short __far *bios_word(unsigned short offset)
{
    return (volatile unsigned short __far *)(unsigned long)offset;
}

static unsigned short normalized_length(const unsigned char *text,
                                        unsigned short length)
{
    unsigned short input;
    unsigned short output = 0;
    for (input = 0; input < length; ++input) {
        if (text[input] == '\r' && input + 1 < length && text[input + 1] == '\n')
            ++input;
        ++output;
    }
    return output;
}

unsigned short pc98_bios_encode_key(const unsigned char *text,
                                    unsigned short length,
                                    unsigned short *input)
{
    unsigned char character = text[*input];
    unsigned char scan = 0;
    if (character == '\r') {
        scan = PC98_SCAN_RETURN;
        if (*input + 1 < length && text[*input + 1] == '\n')
            ++*input;
    } else if (character == '\n') {
        character = '\r';
        scan = PC98_SCAN_RETURN;
    } else if (character == '\b') {
        scan = PC98_SCAN_BACKSPACE;
    } else if (character == '\t') {
        scan = PC98_SCAN_TAB;
    } else if (character == 0x1b) {
        scan = PC98_SCAN_ESC;
    }
    return (unsigned short)character | ((unsigned short)scan << 8);
}

/* Enqueue one already encoded PC-98 BIOS key word. Returns zero when the
   queue is full or its BIOS metadata is invalid. Safe for bounded calls
   from the DOS idle hook; existing keys are never overwritten. */
int pc98_bios_enqueue_word(unsigned short key)
{
    volatile unsigned char __far *count = bios_byte(PC98_KB_COUNT);
    volatile unsigned short __far *tail = bios_word(PC98_KB_TAIL);
    unsigned short position;
    unsigned short flags;

    __asm__ volatile ("pushf; popw %0; cli" : "=r" (flags) : : "cc");
    position = *tail;
    if (*count >= PC98_KB_CAPACITY || position < PC98_KB_BUFFER_START ||
        position >= PC98_KB_BUFFER_END || (position & 1)) {
        __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
        return 0;
    }
    *bios_word(position) = key;
    position += 2;
    if (position >= PC98_KB_BUFFER_END)
        position = PC98_KB_BUFFER_START;
    *tail = position;
    ++*count;
    __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
    return 1;
}

/* Consume only the newest physical Space generated by the Shift+Space
   hotkey.  Leave all earlier user input untouched. */
int pc98_bios_discard_hotkey_space(void)
{
    volatile unsigned char __far *count = bios_byte(PC98_KB_COUNT);
    volatile unsigned short __far *tail = bios_word(PC98_KB_TAIL);
    unsigned short position;
    unsigned short key;
    unsigned short flags;

    __asm__ volatile ("pushf; popw %0; cli" : "=r" (flags) : : "cc");
    position = *tail;
    if (!*count || position < PC98_KB_BUFFER_START ||
        position >= PC98_KB_BUFFER_END || (position & 1)) {
        __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
        return 0;
    }
    position = position == PC98_KB_BUFFER_START
        ? PC98_KB_BUFFER_END - 2
        : position - 2;
    key = *bios_word(position);
    if ((unsigned char)key != ' ' ||
        (unsigned char)(key >> 8) != PC98_SCAN_SPACE) {
        __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
        return 0;
    }
    *tail = position;
    --*count;
    __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
    return 1;
}

/* Returns 1 when queued, and -1 when user keystrokes are already queued or
   the payload cannot fit. Existing input is never overwritten. */
int pc98_bios_inject(const unsigned char *text, unsigned short length)
{
    volatile unsigned char __far *count = bios_byte(PC98_KB_COUNT);
    volatile unsigned short __far *head = bios_word(PC98_KB_HEAD);
    volatile unsigned short __far *tail = bios_word(PC98_KB_TAIL);
    unsigned short position;
    unsigned short flags;
    unsigned short output_length;
    unsigned short key;
    unsigned short i;

    output_length = normalized_length(text, length);
    if (!output_length || output_length > PC98_KB_CAPACITY ||
        *count != 0 || *head != *tail)
        return -1;

    __asm__ volatile ("pushf; popw %0; cli" : "=r" (flags) : : "cc");
    for (i = 0; i < length; ++i) {
        if (*count >= PC98_KB_CAPACITY) {
            __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
            return -1;
        }
        position = *tail;
        key = pc98_bios_encode_key(text, length, &i);
        *bios_word(position) = key;
        position += 2;
        if (position >= PC98_KB_BUFFER_END)
            position = PC98_KB_BUFFER_START;
        *tail = position;
        ++*count;
    }
    __asm__ volatile ("pushw %0; popf" : : "r" (flags) : "cc");
    return 1;
}

/* Returns 1 when every byte survived the BIOS queue, 0 on mismatch, and
   -1 when the injection preconditions are not satisfied. */
int pc98_bios_inject_verify(const unsigned char *text, unsigned short length)
{
    unsigned short ax;
    unsigned short bx;
    unsigned short input;
    unsigned short expected;

    if (pc98_bios_inject(text, length) < 0)
        return -1;

    for (input = 0; input < length; ++input) {
        expected = pc98_bios_encode_key(text, length, &input);
        ax = 0x0500;
        bx = 0;
        __asm__ volatile ("int $0x18" : "+a" (ax), "+b" (bx) : : "cc");
        if (!(bx & 0x0100) || ax != expected)
            return 0;
    }
    return 1;
}
